# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba33a970c952674978ee1a9da89af25ddddfc68a1bbda3df8187b0f0735e9a59ce51514ad79129e0a8905281c0ffe73d77dbbb425b849046f763af2827f61bf

test:
  secret_key_base: 2744ccaf90f83d5b4db05b64a38c1edc08184b8326a340ba02e3ec492231dfd7eaba43b9e7dfb4cdf9ffad304458e3564efb60509e1b89974293959b3e9b1d52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
